local tbl = 
{
	ActionData = 
	{
		[7559] = 
		{
			AffectsPosition = false,
			Aspect = false,
			AttackTypeTargetID = false,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 7559,
			Icon = "/i/000000/000869.png",
			Name = "Surecast",
			TargetArea = false,
		},
		[7560] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 7560,
			Icon = "/i/000000/000861.png",
			Name = "Addle",
			TargetArea = false,
		},
		[7561] = 
		{
			AffectsPosition = false,
			Aspect = false,
			AttackTypeTargetID = false,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 7561,
			Icon = "/i/000000/000866.png",
			Name = "Swiftcast",
			TargetArea = false,
		},
		[7562] = 
		{
			AffectsPosition = false,
			Aspect = false,
			AttackTypeTargetID = false,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 7562,
			Icon = "/i/000000/000865.png",
			Name = "Lucid Dreaming",
			TargetArea = false,
		},
		[11383] = 
		{
			AffectsPosition = false,
			Aspect = 3,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11383,
			Icon = "/i/003000/003251.png",
			Name = "Snort",
			TargetArea = false,
		},
		[11384] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 3,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11384,
			Icon = "/i/003000/003252.png",
			Name = "4-tonze Weight",
			TargetArea = true,
		},
		[11385] = 
		{
			AffectsPosition = false,
			Aspect = 6,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11385,
			Icon = "/i/003000/003253.png",
			Name = "Water Cannon",
			TargetArea = false,
		},
		[11386] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11386,
			Icon = "/i/003000/003254.png",
			Name = "Song of Torment",
			TargetArea = false,
		},
		[11387] = 
		{
			AffectsPosition = false,
			Aspect = 5,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11387,
			Icon = "/i/003000/003255.png",
			Name = "High Voltage",
			TargetArea = false,
		},
		[11388] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11388,
			Icon = "/i/003000/003256.png",
			Name = "Bad Breath",
			TargetArea = false,
		},
		[11389] = 
		{
			AffectsPosition = true,
			Aspect = 7,
			AttackTypeTargetID = 3,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11389,
			Icon = "/i/003000/003257.png",
			Name = "Flying Frenzy",
			TargetArea = false,
		},
		[11390] = 
		{
			AffectsPosition = false,
			Aspect = 6,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11390,
			Icon = "/i/003000/003258.png",
			Name = "Aqua Breath",
			TargetArea = false,
		},
		[11391] = 
		{
			AffectsPosition = false,
			Aspect = 4,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11391,
			Icon = "/i/003000/003259.png",
			Name = "Plaincracker",
			TargetArea = false,
		},
		[11392] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11392,
			Icon = "/i/003000/003260.png",
			Name = "Acorn Bomb",
			TargetArea = false,
		},
		[11393] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11393,
			Icon = "/i/003000/003261.png",
			Name = "Bristle",
			TargetArea = false,
		},
		[11394] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11394,
			Icon = "/i/003000/003262.png",
			Name = "Mind Blast",
			TargetArea = false,
		},
		[11395] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11395,
			Icon = "/i/003000/003263.png",
			Name = "Blood Drain",
			TargetArea = false,
		},
		[11396] = 
		{
			AffectsPosition = false,
			Aspect = true,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11396,
			Icon = "/i/003000/003264.png",
			Name = "Bomb Toss",
			TargetArea = true,
		},
		[11397] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 2,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11397,
			Icon = "/i/003000/003265.png",
			Name = "1000 Needles",
			TargetArea = false,
		},
		[11398] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 2,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11398,
			Icon = "/i/003000/003266.png",
			Name = "Drill Cannons",
			TargetArea = false,
		},
		[11399] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11399,
			Icon = "/i/003000/003267.png",
			Name = "the Look",
			TargetArea = false,
		},
		[11400] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = true,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11400,
			Icon = "/i/003000/003268.png",
			Name = "Sharpened Knife",
			TargetArea = false,
		},
		[11401] = 
		{
			AffectsPosition = true,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11401,
			Icon = "/i/003000/003269.png",
			Name = "Loom",
			TargetArea = true,
		},
		[11402] = 
		{
			AffectsPosition = false,
			Aspect = true,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11402,
			Icon = "/i/003000/003270.png",
			Name = "Flame Thrower",
			TargetArea = false,
		},
		[11403] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11403,
			Icon = "/i/003000/003271.png",
			Name = "Faze",
			TargetArea = false,
		},
		[11404] = 
		{
			AffectsPosition = false,
			Aspect = 5,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11404,
			Icon = "/i/003000/003272.png",
			Name = "Glower",
			TargetArea = false,
		},
		[11405] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11405,
			Icon = "/i/003000/003273.png",
			Name = "Missile",
			TargetArea = false,
		},
		[11406] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11406,
			Icon = "/i/003000/003274.png",
			Name = "White Wind",
			TargetArea = false,
		},
		[11407] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 2,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11407,
			Icon = "/i/003000/003275.png",
			Name = "Final Sting",
			TargetArea = false,
		},
		[11408] = 
		{
			AffectsPosition = false,
			Aspect = true,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11408,
			Icon = "/i/003000/003276.png",
			Name = "Self-destruct",
			TargetArea = false,
		},
		[11409] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = true,
			CanTargetSelf = false,
			ID = 11409,
			Icon = "/i/003000/003277.png",
			Name = "Transfusion",
			TargetArea = false,
		},
		[11410] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11410,
			Icon = "/i/003000/003278.png",
			Name = "Toad Oil",
			TargetArea = false,
		},
		[11411] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11411,
			Icon = "/i/003000/003279.png",
			Name = "Off-guard",
			TargetArea = false,
		},
		[11412] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 3,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11412,
			Icon = "/i/003000/003280.png",
			Name = "Sticky Tongue",
			TargetArea = false,
		},
		[11413] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11413,
			Icon = "/i/003000/003281.png",
			Name = "Tail Screw",
			TargetArea = false,
		},
		[11414] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11414,
			Icon = "/i/003000/003282.png",
			Name = "Level 5 Petrify",
			TargetArea = false,
		},
		[11415] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11415,
			Icon = "/i/003000/003283.png",
			Name = "Moon Flute",
			TargetArea = false,
		},
		[11416] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11416,
			Icon = "/i/003000/003284.png",
			Name = "Doom",
			TargetArea = false,
		},
		[11417] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11417,
			Icon = "/i/003000/003285.png",
			Name = "Mighty Guard",
			TargetArea = false,
		},
		[11418] = 
		{
			AffectsPosition = false,
			Aspect = 2,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11418,
			Icon = "/i/003000/003286.png",
			Name = "Ice Spikes",
			TargetArea = false,
		},
		[11419] = 
		{
			AffectsPosition = false,
			Aspect = 2,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11419,
			Icon = "/i/003000/003287.png",
			Name = "the Ram's Voice",
			TargetArea = false,
		},
		[11420] = 
		{
			AffectsPosition = false,
			Aspect = 5,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11420,
			Icon = "/i/003000/003288.png",
			Name = "the Dragon's Voice",
			TargetArea = false,
		},
		[11421] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11421,
			Icon = "/i/003000/003289.png",
			Name = "Peculiar Light",
			TargetArea = false,
		},
		[11422] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11422,
			Icon = "/i/003000/003290.png",
			Name = "Ink Jet",
			TargetArea = false,
		},
		[11423] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 2,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11423,
			Icon = "/i/003000/003291.png",
			Name = "Flying Sardine",
			TargetArea = false,
		},
		[11424] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11424,
			Icon = "/i/003000/003292.png",
			Name = "Diamondback",
			TargetArea = false,
		},
		[11425] = 
		{
			AffectsPosition = false,
			Aspect = true,
			AttackTypeTargetID = 2,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11425,
			Icon = "/i/003000/003293.png",
			Name = "Fire Angon",
			TargetArea = false,
		},
		[11426] = 
		{
			AffectsPosition = false,
			Aspect = 3,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11426,
			Icon = "/i/003000/003294.png",
			Name = "Feather Rain",
			TargetArea = true,
		},
		[11427] = 
		{
			AffectsPosition = false,
			Aspect = true,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11427,
			Icon = "/i/003000/003295.png",
			Name = "Eruption",
			TargetArea = true,
		},
		[11428] = 
		{
			AffectsPosition = false,
			Aspect = 4,
			AttackTypeTargetID = 3,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11428,
			Icon = "/i/003000/003296.png",
			Name = "Mountain Buster",
			TargetArea = false,
		},
		[11429] = 
		{
			AffectsPosition = false,
			Aspect = 5,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 11429,
			Icon = "/i/003000/003297.png",
			Name = "Shock Strike",
			TargetArea = false,
		},
		[11430] = 
		{
			AffectsPosition = false,
			Aspect = 2,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11430,
			Icon = "/i/003000/003298.png",
			Name = "Glass Dance",
			TargetArea = false,
		},
		[11431] = 
		{
			AffectsPosition = false,
			Aspect = 6,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 11431,
			Icon = "/i/003000/003299.png",
			Name = "Veil of the Whorl",
			TargetArea = false,
		},
		[11715] = 
		{
			AffectsPosition = false,
			CanTargetDead = true,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ClassJobLevel = 0,
			IsPlayerAction = false,
			IsPvP = false,
			IsRoleAction = false,
			Name = "0",
			TargetArea = false,
		},
		[18295] = 
		{
			AffectsPosition = false,
			Aspect = 3,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18295,
			Icon = "/i/003000/003300.png",
			Name = "Alpine Draft",
			TargetArea = false,
		},
		[18296] = 
		{
			AffectsPosition = false,
			Aspect = 6,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18296,
			Icon = "/i/003000/003301.png",
			Name = "Protean Wave",
			TargetArea = false,
		},
		[18297] = 
		{
			AffectsPosition = false,
			Aspect = 2,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18297,
			Icon = "/i/003000/003302.png",
			Name = "Northerlies",
			TargetArea = false,
		},
		[18298] = 
		{
			AffectsPosition = false,
			Aspect = 5,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18298,
			Icon = "/i/003000/003303.png",
			Name = "Electrogenesis",
			TargetArea = false,
		},
		[18299] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = true,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18299,
			Icon = "/i/003000/003304.png",
			Name = "Kaltstrahl",
			TargetArea = false,
		},
		[18300] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 2,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18300,
			Icon = "/i/003000/003305.png",
			Name = "Abyssal Transfixion",
			TargetArea = false,
		},
		[18301] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18301,
			Icon = "/i/003000/003306.png",
			Name = "Chirp",
			TargetArea = false,
		},
		[18302] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18302,
			Icon = "/i/003000/003307.png",
			Name = "Eerie Soundwave",
			TargetArea = false,
		},
		[18303] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = true,
			CanTargetHostile = false,
			CanTargetParty = true,
			CanTargetSelf = true,
			ID = 18303,
			Icon = "/i/003000/003308.png",
			Name = "Pom Cure",
			TargetArea = false,
		},
		[18304] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18304,
			Icon = "/i/003000/003309.png",
			Name = "Gobskin",
			TargetArea = false,
		},
		[18305] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18305,
			Icon = "/i/003000/003310.png",
			Name = "Magic Hammer",
			TargetArea = false,
		},
		[18306] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = true,
			CanTargetSelf = false,
			ID = 18306,
			Icon = "/i/003000/003311.png",
			Name = "Avail",
			TargetArea = false,
		},
		[18307] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18307,
			Icon = "/i/003000/003312.png",
			Name = "Frog Legs",
			TargetArea = false,
		},
		[18308] = 
		{
			AffectsPosition = false,
			Aspect = 3,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18308,
			Icon = "/i/003000/003313.png",
			Name = "Sonic Boom",
			TargetArea = false,
		},
		[18309] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18309,
			Icon = "/i/003000/003314.png",
			Name = "Whistle",
			TargetArea = false,
		},
		[18310] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18310,
			Icon = "/i/003000/003315.png",
			Name = "White Knight's Tour",
			TargetArea = false,
		},
		[18311] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18311,
			Icon = "/i/003000/003316.png",
			Name = "Black Knight's Tour",
			TargetArea = false,
		},
		[18312] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18312,
			Icon = "/i/003000/003317.png",
			Name = "Level 5 Death",
			TargetArea = false,
		},
		[18313] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18313,
			Icon = "/i/003000/003318.png",
			Name = "Launcher",
			TargetArea = false,
		},
		[18314] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18314,
			Icon = "/i/003000/003319.png",
			Name = "Perpetual Ray",
			TargetArea = false,
		},
		[18315] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = true,
			CanTargetSelf = false,
			ID = 18315,
			Icon = "/i/003000/003320.png",
			Name = "Cactguard",
			TargetArea = false,
		},
		[18316] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 3,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18316,
			Icon = "/i/003000/003321.png",
			Name = "Revenge Blast",
			TargetArea = false,
		},
		[18317] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = true,
			CanTargetHostile = false,
			CanTargetParty = true,
			CanTargetSelf = false,
			ID = 18317,
			Icon = "/i/003000/003322.png",
			Name = "Angel Whisper",
			TargetArea = false,
		},
		[18318] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18318,
			Icon = "/i/003000/003323.png",
			Name = "Exuviation",
			TargetArea = false,
		},
		[18319] = 
		{
			AffectsPosition = false,
			Aspect = 5,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18319,
			Icon = "/i/003000/003324.png",
			Name = "Reflux",
			TargetArea = false,
		},
		[18320] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18320,
			Icon = "/i/003000/003325.png",
			Name = "Devour",
			TargetArea = false,
		},
		[18321] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18321,
			Icon = "/i/003000/003326.png",
			Name = "Condensed Libra",
			TargetArea = false,
		},
		[18322] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = true,
			CanTargetHostile = false,
			CanTargetParty = true,
			CanTargetSelf = false,
			ID = 18322,
			Icon = "/i/003000/003327.png",
			Name = "Aetherial Mimicry",
			TargetArea = false,
		},
		[18323] = 
		{
			AffectsPosition = false,
			Aspect = 4,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18323,
			Icon = "/i/003000/003328.png",
			Name = "Surpanakha",
			TargetArea = false,
		},
		[18324] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 18324,
			Icon = "/i/003000/003329.png",
			Name = "Quasar",
			TargetArea = false,
		},
		[18325] = 
		{
			AffectsPosition = true,
			Aspect = 7,
			AttackTypeTargetID = 3,
			CanTargetFriendly = false,
			CanTargetHostile = true,
			CanTargetParty = false,
			CanTargetSelf = false,
			ID = 18325,
			Icon = "/i/003000/003330.png",
			Name = "J Kick",
			TargetArea = false,
		},
		[19238] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 19238,
			Icon = "/i/003000/003327.png",
			Name = "Aetherial Mimicry",
			TargetArea = false,
		},
		[19239] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 19239,
			Icon = "/i/003000/003327.png",
			Name = "Aetherial Mimicry",
			TargetArea = false,
		},
		[19240] = 
		{
			AffectsPosition = false,
			Aspect = 7,
			AttackTypeTargetID = 5,
			CanTargetFriendly = false,
			CanTargetHostile = false,
			CanTargetParty = false,
			CanTargetSelf = true,
			ID = 19240,
			Icon = "/i/003000/003327.png",
			Name = "Aetherial Mimicry",
			TargetArea = false,
		},
	},
	ActionDelay = 500,
	ActionDelays = 
	{
		[7559] = 0,
		[7560] = 0,
		[7561] = 0,
		[7562] = 0,
		[11383] = 0,
		[11384] = 0,
		[11385] = 0,
		[11386] = 4500,
		[11387] = 0,
		[11388] = 5000,
		[11389] = 0,
		[11390] = 0,
		[11391] = 0,
		[11392] = 0,
		[11393] = 5000,
		[11394] = 0,
		[11395] = 0,
		[11396] = 0,
		[11397] = 0,
		[11398] = 0,
		[11399] = 0,
		[11400] = 0,
		[11401] = 0,
		[11402] = 0,
		[11403] = 15000,
		[11404] = 0,
		[11405] = 0,
		[11406] = 0,
		[11407] = 0,
		[11408] = 0,
		[11409] = 0,
		[11410] = 5000,
		[11411] = 0,
		[11412] = 0,
		[11413] = 0,
		[11414] = 0,
		[11415] = 0,
		[11416] = 0,
		[11417] = 0,
		[11418] = 5000,
		[11419] = 0,
		[11420] = 5000,
		[11421] = 0,
		[11422] = 0,
		[11423] = 0,
		[11424] = 0,
		[11425] = 0,
		[11426] = 0,
		[11427] = 0,
		[11428] = 0,
		[11429] = 0,
		[11430] = 0,
		[11431] = 0,
		[18295] = 0,
		[18296] = 0,
		[18297] = 0,
		[18298] = 0,
		[18299] = 0,
		[18300] = 0,
		[18301] = 0,
		[18302] = 1000,
		[18303] = 0,
		[18304] = 0,
		[18305] = 0,
		[18306] = 0,
		[18307] = 0,
		[18308] = 0,
		[18309] = 0,
		[18310] = 0,
		[18311] = 0,
		[18312] = 0,
		[18313] = 0,
		[18314] = 0,
		[18315] = 0,
		[18316] = 0,
		[18317] = 0,
		[18318] = 2000,
		[18319] = 0,
		[18320] = 0,
		[18321] = 1500,
		[18322] = 1500,
		[18323] = 0,
		[18324] = 0,
		[18325] = 0,
		[107561] = 0,
		[111385] = 0,
		[111396] = 0,
		[111397] = 0,
		[111400] = 0,
		[111425] = 0,
		[118295] = 0,
		[118298] = 0,
		[118308] = 0,
		[211396] = 0,
		[218298] = 0,
		[311396] = 0,
	},
	ActionLogic = 
	{
		[7561] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(7561)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and player.incombat then\n\t\tlocal actions,ids = BLU.Data.Action, BLU.Settings.SwiftCastActions\n\t\tif valid(2,actions,ids) then\n\t\t\t\tfor i=1,#ids do\n\t\t\t\t\t\tlocal id = ids[i]\n\t\t\t\t\t\tlocal action = actions[id]\n\t\t\t\t\t\tif valid(action) then\n\t\t\t\t\t\t\t\tif action.usable and BLU.CD(action) <= BLU.Settings.PrecastTime then\n\t\t\t\t\t\t\t\t\t\tlocal skip,check = BLU.Data.ActionLogic[id]()\n\t\t\t\t\t\t\t\t\t\tif check then\n\t\t\t\t\t\t\t\t\t\t\t\treturn true,player\n\t\t\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Next action's cast time is reduced to zero --",
		[7562] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(7562)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif TimeSince(BLU.Data.LastCombat) < 20000 and player.mp.percent < 60 then\n\t\treturn true,player\nend\nreturn false\n\n-- Gradually Restores MP --",
		[11384] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11384)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElGroundCheck(el,player,target,range,radius,2)\nend\nreturn false\n\n-- TODO: Add Heavy Check",
		[11385] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11385)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and MissingBuffs(player,\"167+1716\") then\n\t\tif valid(target) then\n  \t\tif BLU.ValidEntity(player,target,target,range) then\n    \t\treturn true,target\n  \t\tend\n\t\tend\n\t\t-- if valid(el) then\n\t\t-- \t\tfor id,entity in pairs(el) do\n\t\t-- \t\t\t\tif BLU.ValidEntity(player,target,entity,range) then\n\t\t-- \t\t\t\t\t\treturn true,entity\n\t\t-- \t\t\t\tend\n\t\t-- \t\tend\n\t\t-- end\n\nend\nreturn false",
		[11386] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11386)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and valid(target) and player.incombat then\n  local check = function(entity)\n\t\t\t\tif MissingBuffs(entity,\"1714\",6) then\n\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n  if BLU.ValidEntity(player,target,target,range,check) then\n    return true,target\n\t\tend\n\n\t\t-- elseif HasBuffs(player,\"1716\") and valid(el) then\n\t\t-- \t\tfor _,entity in pairs(el) do\n\t\t-- \t\t\t\tlocal check = function(entity) if entity.incombat and MissingBuffs(entity,\"1714\",2) then return true end end\n\t\t-- \t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t-- \t\t\t\t\t\treturn true,entity\n\t\t-- \t\t\t\tend\n\t\t-- \t\tend\n  -- end\n\nend\nreturn false",
		[11387] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11387)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false",
		[11388] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11388)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and (HasBuffs(player,\"1720+2124\") or not BLU.Data.Action[18322].usable) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity) if MissingBuffs(entity,\"1715\") then return true end end\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2,check)\nend\nreturn false\n\n-- Inflicts multiple debuffs in cone --",
		[11389] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11389)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[3].enable and valid(el) and NotBound() then\n    local result,pos,id = BLU.ElAroundTargetCheck(el,player,target,range,radius,2)\n    if result then\n        return true,pos\n    end\nend\nreturn false",
		[11390] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11390)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2)\nend\nreturn false",
		[11391] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11391)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false",
		[11393] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11393)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and player.incombat then\n\t\tlocal actions,ids = BLU.Data.Action, BLU.Settings.BristleActions\n\t\tif valid(2,actions,ids) then\n\t\t\t\tfor i=1,#ids do\n\t\t\t\t\t\tlocal id = ids[i]\n\t\t\t\t\t\tlocal action = actions[id]\n\t\t\t\t\t\tif valid(action) and action.usable and BLU.CD(action) <= BLU.Settings.PrecastTime then\n\t\t\t\t\t\t\t\tlocal skip,check = BLU.Data.ActionLogic[id]()\n\t\t\t\t\t\t\t\tif check then\n\t\t\t\t\t\t\t\t\t\treturn true,player\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false",
		[11394] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11394)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false",
		[11395] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11395)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\t-- local tankBuffs = HasBuffs(player,\"1710+2124\")\n\t\tlocal mpp = player.mp.percent\n\t\tif valid(target) and BLU.ValidEntity(player,target,target,range) then\n\t\t\t\tif target.targetid == player.id and mpp <= BLU.Settings.playerTankRestoreMpPercent then\n\t\t\t\t\t\treturn true,target\n\t\t\t\telseif mpp <= BLU.Settings.playerRestoreMpPercent then\n\t\t\t\t\t\treturn true,target\n\t\t\t\tend\n\t\telseif valid(el) then\n\t\t\t\tfor _,entity in pairs(el) do\n\t\t\t\t\t\tif entity.incombat and BLU.ValidEntity(player,target,entity,range) then\n\t\t\t\t\t\t\t\tif entity.targetid == player.id and mpp <= BLU.Settings.playerTankRestoreMpPercent then\n\t\t\t\t\t\t\t\t\t\treturn true,entity\n\t\t\t\t\t\t\t\telseif mpp <= BLU.Settings.playerRestoreMpPercent then\n\t\t\t\t\t\t\t\t\t\treturn true,entity\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Recovers 500 MP --",
		[11396] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11396)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity)\n\t\t\t\tlocal result,remaining = IsChanneling(entity,BLU.Settings.StunCastingIDs)\n\t\t\t\tif result and action.casttime <= remaining then return true end end\n\t\tlocal result,pos,id = BLU.ElGroundCheck(el,player,target,range,radius,2,check)\n\t\tif result then\n\t\t\t\tBLU.Data.lastStunTarget = id\n\t\t\t\treturn true,pos\n\t\tend\nend\nreturn false\n\n-- Stuns all enemies in a circle at a designated location --",
		[11397] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11397)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and lastcast ~= 11393 and player.incombat and valid(el) then\n\t\treturn true,player\nend\nreturn false\n\n-- Does a flat 1000 damage split between all enemies around Player --",
		[11398] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11398)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,2)\nend\nreturn false\n\n-- TODO: Add Petrify Check",
		[11399] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11399)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and HasBuffs(player,\"2124\") and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.334,el,player,target,radius,2)\nend\nreturn false",
		[11400] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11400)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\tif valid(target) then\n\t\t\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\t\t\tif HasBuffs(entity,\"2\",1) or TimeSince(BLU.Data.LastCast[11403] or 0) <= actiondelay then return true end end\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,target,range,check) then\n\t\t\t\t\t\t\t\treturn true,target\n\t\t\t\t\t\tend\n\t\tend\n\t\tif valid(el) then\n\t\t\t\tfor id,entity in pairs(el) do\n\t\t\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\t\t\tif HasBuffs(entity,\"2\",1) then return true end end\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t\t\t\t\t\t\treturn true,entity\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false",
		[11401] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11401)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[3].enable then\nend\nreturn false",
		[11402] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11402)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.334,el,player,target,radius,2)\nend\nreturn false",
		[11403] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11403)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity) if MissingBuffs(entity,\"2\") then return true end end\n\t\tlocal result,Target,id = BLU.ElConeCheck(0.251,el,player,target,radius,2,check)\n\t\tif result then\n  \t\tBLU.Data.lastStunTarget = id\n\t\t\t\treturn true,Target\n\t\tend\nend\n\n-- Stuns all enemies in a cone before you --",
		[11404] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11404)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,2)\nend\nreturn false",
		[11405] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11405)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[7].enable and BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal hp,CastTarget = 0,{}\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tlocal elvl,plvl = entity.level,player.level\n\t\t\t\tif elvl <= plvl then\n\t\t\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t\t\t\t\t\t\tlocal ehp = entity.hp\n\t\t\t\t\t\t\t\tif ehp.current > hp then\n\t\t\t\t\t\t\t\t\t\thp,CastTarget = ehp.current,entity\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\n\t\tif hp > 0 then\n\t\t\t\treturn true,CastTarget\n\t\tend\nend\nreturn false\n\n-- Damage equal to half target's current hp, low chance --",
		[11406] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11406)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif TimeSince(BLU.Data.LastCombat) < 10000 and BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\tif player.hp.percent < BLU.Settings.playerCurePercent then\n\t\t\t\treturn true,player\n\t\tend\n\t\tlocal party = MEntityList(\"friendly,alive,chartype=4,myparty,targetable,maxdistance=\"..tostring(radius))\n\t\tif valid(party) then\n\t\t\t\tlocal count = 0\n\t\t\t\tfor id,member in pairs(party) do\n\t\t\t\t\t\tif member.hp.percent < BLU.Settings.partyCurePercent then\n\t\t\t\t\t\t\t\tcount = count + 1\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\t\t\tif count > 0 then\n\t\t\t\t\t\treturn true,player\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Restores own and party HP equal to your current HP --",
		[11407] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11407)\n--- DO NOT EDIT ABOVE THIS LINE ---\n\n-- Instnat Kill Attack, Queued Action Only --",
		[11408] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11408)\n--- DO NOT EDIT ABOVE THIS LINE ---\n\n-- Instnat Kill Attack, Queued Action Only --",
		[11409] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11409)\n--- DO NOT EDIT ABOVE THIS LINE ---\n\n-- Instnat Kill Attack, Queued Action Only --",
		[11410] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11410)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif not IsCityMap(player.localmapid) and BLU.Not(lastcast,7561,11393,11410) and MissingBuffs(player,\"167\") and MissingBuffs(player,\"1737\",10) then\n\t\tif player.incombat then\n\t\t\t\tel = MEntityList(\"los,alive,attackable,targetable,targetingme,incombat,maxdistance2d=25,exclude_contentid=541\")\n\t\t\t\tif valid(el) then\n\t\t\t\t\t\treturn true,player\n\t\t\t\tend\n\t\tend\n\t\tlocal lastmove,laststop = BLU.Data.LastMove,BLU.Data.LastStop\n\t\tif TimeSince(lastmove) < 175000 and TimeSince(laststop) > 700 then\n\t\t\t\treturn true,player\n\t\telseif lastmove == 0 then\n\t\t\t\tBLU.Data.LastMove = Now()\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false\n\n-- Increases Evasion --",
		[11411] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11411)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(target) and MissingBuffs(player,\"167\") then\n\t\tlocal party = MEntityList(\"myparty\")\n\t\tif target.contentid == 541 then return true\n\t\telseif valid(party) then\n\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\tif MissingBuffs(entity,\"1717\",2) then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n\t\t\t\tif BLU.ValidEntity(player,target,target,range,check(target)) then\n\t\t\t\t\t\treturn true,target\n\t\t\t\tend\n\t\telse\n\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\tif MissingBuffs(entity,\"1717\",2) then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n\t\t\t\tif BLU.ValidEntity(player,target,target,range,check(target)) then\n\t\t\t\t\t\treturn true,target\n\t\t\t\tend\n\t\tend\nend\nreturn false",
		[11412] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11412)\n--- DO NOT EDIT ABOVE THIS LINE ---\n\n-- Some ideas include, pulling enemies towards you that you lost aggro on that's targeting a non tank role\n\n-- Auto pulling in certain enemies for mechanics, maybe when you're near certain objects / entities",
		[11413] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11413)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[7].enable and BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal hp,CastTarget = 0,{}\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tlocal elvl,plvl = entity.level,player.level\n\t\t\t\tif elvl <= plvl then\n\t\t\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t\t\t\t\t\t\tlocal ehp = entity.hp\n\t\t\t\t\t\t\t\tif ehp.current > hp then\n\t\t\t\t\t\t\t\t\t\thp,CastTarget = ehp.current,entity\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\n\t\tif hp > 0 then\n\t\t\t\treturn true,CastTarget\n\t\tend\nend\nreturn false\n\n-- Low Chance to drop target's HP to 1 --",
		[11416] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11416)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[7].enable and BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal hp,CastTarget = 0,{}\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tlocal elvl,plvl = entity.level,player.level\n\t\t\t\tif elvl <= plvl then\n\t\t\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t\t\t\t\t\t\tlocal ehp = entity.hp\n\t\t\t\t\t\t\t\tif ehp.current > hp then\n\t\t\t\t\t\t\t\t\t\thp,CastTarget = ehp.current,entity\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\n\t\tif hp > 0 then\n\t\t\t\treturn true,CastTarget\n\t\tend\nend\nreturn false\n\n-- Doom, Low Chance --",
		[11418] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11418)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(target) and MissingBuffs(player,\"1720\",1) and MissingBuffs(player,\"167+1716\") then\n\t\tif player.hp.percent < BLU.Settings.playerSpikeBuffAttacksLT then\n\t\t\t\tel = MEntityList(\"los,alive,attackable,targetable,targetingme,incombat,maxdistance2d=25,exclude_contentid=541\")\n\t\t\t\tif valid(el) then\n\t\t\t\t\t\treturn true,player\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Counters any enemy with paralyze --",
		[11419] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11419)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false",
		[11420] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11420)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal count = 0\n\t\tfor id,entity in pairs(el) do\n\t\t\t\tlocal check = function(entity) if BLU.Distance3D(Player,entity) >= 8 and HasBuffs(entity,\"1731\") then return true end end\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius,check) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend",
		[11421] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11421)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tlocal check = function(entity) if MissingBuffs(entity,\"1721\") then return true end end\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius,check) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false",
		[11422] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11422)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2)\nend\nreturn false",
		[11423] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11423)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) then\n  for id,entity in pairs(el) do\n\t\t\t\tlocal result,remaining = IsChanneling(entity, BLU.Settings.InterruptIDs)\n\t\t\t\tif result and action.casttime <= remaining then\n\t\t\t\t\t\tBLU.Data.lastInterruptTarget = id\n\t\t\t\t\t\treturn true,entity\n\t\t\t\tend\n\t\tend\nend\nreturn false \n\n-- Interrupts Single Target --",
		[11424] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11424)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) then\n  for id,entity in pairs(el) do\n\t\t\t\tif entity.incombat then\n\t\t\t\t\t\tlocal result,remaining,targetid = IsChanneling(entity, BLU.Settings.DiamondbackTargetIDs)\n\t\t\t\t\t\tif result and action.casttime <= (remaining - 1) and targetid == player.id then\n\t\t\t\t\t\t\t\treturn true,player\n\t\t\t\t\t\tend\n\t\t\t\t\t\tlocal result,remaining = IsChanneling(entity, BLU.Settings.DiamondbackAoEIDs)\n\t\t\t\t\t\tif result and action.casttime <= (remaining - 1) then\n\t\t\t\t\t\t\t\treturn true,player\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false",
		[11425] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11425)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n    local check = function(entity)\n\t\t\t\t\t\tlocal tbl = {9234,9235,9236,9237,9238}\n\t\t\t\t\t\tif table.contains(tbl,entity.contentid) then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n    local result,pos,id = BLU.ElAroundTargetCheck(el,player,target,range,radius,2,check)\n    if result then\n        return true,pos\n    end\nend\nreturn false",
		[11426] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11426)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) and valid(target) then\n  local check = function(entity)\n\t\t\t\tif entity.contentid ~= 9233 and MissingBuffs(entity,556) then\n\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n  local check2 = function(entity)\n\t\t\t\tif MissingBuffs(entity,556) then\n\t\t\t\t\t\treturn true end end\n    return BLU.ElGroundCheck(el,player,target,range,radius,1,check,check2)\nend\nreturn false\n\n-- Ground AoE Attack with strong DoT --",
		[11427] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11427)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) then\n    local check = function(entity)\n\t\t\t\t\t\tif entity.contentid ~= 9233 then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n    local result,pos,id = BLU.ElGroundCheck(el,player,target,range,radius,1,check)\n    if result then\n        return true,pos\n    end\nend\nreturn false\n\n-- Ground AoE Attack --",
		[11428] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11428)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) and valid(target) then\n  local check = function(entity)\n\t\t\t\treturn BLU.HpAdvantage(entity) end\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,1,check)\nend\nreturn false\n\n-- Frontal Cone Attack --",
		[11429] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11429)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) and valid(target) then\n\t\tlocal check = function(entity)\n\t\t\t\treturn BLU.HpAdvantage(entity) end\n  return BLU.ElAroundTargetCheck(el,player,target,range,radius,1,check)\nend\nreturn false\n\n-- Ground AoE Attack --",
		[11430] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11430)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(el) and valid(target) then\n  local check = function(entity)\n\t\t\t\tif MissingBuffs(entity,556) then\n\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n  local check2 = function(entity)\n\t\t\t\tif MissingBuffs(entity,556) then\n\t\t\t\t\t\treturn true end end\n\t\treturn BLU.ElConeCheck(0.65,el,player,target,radius,1,check,check2)\nend\nreturn false\n\n-- Stupid Wide Frontal Cone Attack --",
		[11431] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11431)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(target) and HasBuffs(player,\"1720+2124\") and MissingBuffs(player,\"167+1716\") then\n\t\tif player.hp.percent < BLU.Settings.playerSpikeBuffAttacksLT then\n\t\t\t\tel = MEntityList(\"los,alive,attackable,targetable,targetingme,incombat,maxdistance2d=25,exclude_contentid=541\")\n\t\t\t\tif valid(el) then\n\t\t\t\t\t\treturn true,player\n\t\t\t\tend\n\t\tend\nend\nreturn false",
		[18295] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18295)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity)\n\t\t\t\tlocal CIDs = {9239,9240}\n\t\t\t\tif table.contains(CIDs,entity.contentid) then return true end end\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,2,check)\nend\nreturn false",
		[18296] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18296)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2)\nend\nreturn false",
		[18297] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18297)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2)\nend\nreturn false\n\n-- TODO: Add Modifier Check",
		[18298] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18298)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n    local check = function(entity)\n\t\t\t\t\t\tlocal tbl = {9241,9242,9243,9244}\n\t\t\t\t\t\tif table.contains(tbl,entity.contentid) then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n    local result,pos,id = BLU.ElGroundCheck(el,player,target,range,radius,2,check)\n    if result then\n        return true,pos\n    end\nend\nreturn false",
		[18299] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18299)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2)\nend\nreturn false",
		[18300] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18300)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(target) and MissingBuffs(player,\"167+1716\") then\n  local check = function(entity)\n\t\t\t\tif MissingBuffs(entity,\"17+216+482+988\") then\n\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n  if BLU.ValidEntity(player,target,target,range,check) then\n    return true,target\n\t\tend\nend\nreturn false",
		[18302] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18302)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tif entity.incombat and HasBuffs(entity, table.concat(BLU.Settings.DispelIDs,\",\")) then\n\t\t\t\t\t\treturn true,player\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Dispel --",
		[18303] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18303)\n--- DO NOT EDIT ABOVE THIS LINE ---\nlocal HealerMimicry,value,CastTarget = HasBuffs(player,\"2126\"),0,{}\nif (HealerMimicry or player.hp.percent < 20) and TimeSince(BLU.Data.LastCombat) < 10000 and BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal hpp = Player.hp.percent\n\t\tif hpp <= BLU.Settings.playerCurePercent then value,CastTarget = (100-hpp)*4,player end\n\t\tlocal str = \"friendly,alive,chartype=4,incombat,targetable,maxdistance=\"..tostring(radius)\n\t\tif not BLU.Settings.CureOutsideParty then str = str..\",myparty\" end\n\t\tlocal party = MEntityList(str)\n\t\tif valid(party) then\n\t\t\t\tfor _,member in pairs(party) do\n\t\t\t\t\t\tlocal hpp,role = member.hp.percent,GetRoleString(member.job)\n\t\t\t\t\t\tlocal bluTank,bluHealer = HasBuffs(member,\"2124\"),HasBuffs(member,\"2126\")\n\t\t\t\t\t\tif role == \"tank\" or bluTank and hpp < BLU.Settings.tankCurePercent then\n\t\t\t\t\t\t\t\tvalue,CastTarget = (100-hpp)*3,member\n\t\t\t\t\t\telseif role == \"healer\" or bluHealer and hpp < BLU.Settings.partyCurePercent then\n\t\t\t\t\t\t\t\tvalue,CastTarget = (100-hpp)*2,member\n\t\t\t\t\t\telseif role == \"dps\" and hpp < BLU.Settings.partyCurePercent then\n\t\t\t\t\t\t\t\tvalue,CastTarget = (100-hpp),member\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nif value ~= 0 then\n\t\treturn true,CastTarget\nend\nreturn false\n\n-- Single Target Cure --",
		[18304] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18304)\n--- DO NOT EDIT ABOVE THIS LINE ---\nlocal HealerMimicry = HasBuffs(player,\"2126\")\nif HealerMimicry and TimeSince(BLU.Data.LastCombat) < 10000 and BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal party = MEntityList(\"friendly,alive,chartype=4,myparty,targetable,maxdistance=\"..tostring(radius))\n\t\tif valid(party) then\n\t\t\t\tfor id,member in pairs(party) do\n\t\t\t\t\t\tif player.hp.percent > BLU.Settings.playerCurePercent and member.hp.percent < BLU.Settings.partyCurePercent then\n\t\t\t\t\t\t\t\treturn true,player\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Stoneskin --",
		[18305] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18305)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and player.mp.percent < 80 and MissingBuffs(player,\"167+1716\") then\n\t\tlocal result,pos,id = BLU.ElGroundCheck(el,player,target,range,radius,2)\n\t\tif result then\n\t\t\t\treturn true,pos\n\t\tend\nend\nreturn false\n\n-- Restores 10% of max MP for every enemy hit --",
		[18308] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18308)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and valid(target) and player.incombat then\n  local check = function(entity)\n\t\t\t\tlocal CIDs = {9239,9240}\n\t\t\t\tif table.contains(CIDs,entity.contentid) then return true end end\n  if BLU.ValidEntity(player,target,target,range,check) then\n    return true,target\n  end\nend\nreturn false",
		[18310] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18310)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity) if HasBuffs(entity,\"13\",2) then return true end end\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,2,check)\nend\nreturn false",
		[18311] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18311)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity) if HasBuffs(entity,\"9\",2) then return true end end\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,2,check)\nend\nreturn false",
		[18313] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18313)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[7].enable and BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n\t\t\t\tlocal elvl,plvl = entity.level,player.level\n\t\t\t\tif elvl <= plvl then\n\t\t\t\t\t\tlocal check = function(entity)\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t\t\t\t\t\t\tcount = count + 1\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\n\t\tif count > 2 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false",
		[18314] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18314)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tfor id,entity in pairs(el) do\n\t\tlocal check = function(entity)\n\t\t\t\tlocal result,remaining = IsChanneling(entity,BLU.Settings.StunCastingIDs)\n\t\t\t\tif result and action.casttime <= remaining then return true end end\n\t\t\t\tif BLU.ValidEntity(player,target,entity,range,check) then\n\t\t\t\t\t\tBLU.Data.lastStunTarget = id\n\t\t\t\t\t\treturn true,entity\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Quick Stun, Ignores target's Stun resistance --",
		[18317] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18317)\n--- DO NOT EDIT ABOVE THIS LINE ---\nlocal str = \"friendly,dead,chartype=4,targetable,maxdistance=\"..tostring(range)\nif not BLU.Settings.RaiseOutsideParty then str = str..\",myparty\" end\nlocal party = MEntityList(str)\nif valid(party) then\n\t\tfor id,member in pairs(party) do\n\t\t\t\tif MissingBuffs(member,\"148+1140\") then\n\t\t\t\t\t\tlocal Valid = true\n\t\t\t\t\t\tlocal OtherCasters = MEntityList(\"friendly,chartype=4\")\n\t\t\t\t\t\tif valid(OtherCasters) then\n\t\t\t\t\t\t\t\tfor _,caster in pairs(OtherCasters) do\n\t\t\t\t\t\t\t\t\t\tlocal castTarget = caster.castinginfo.channeltargetid\n\t\t\t\t\t\t\t\t\t\tif castTarget == id then Valid = false end\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\t\t\tif Valid then\n\t\t\t\t\t\t\t\treturn true,member\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Raise --",
		[18318] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18318)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif TimeSince(BLU.Data.LastCombat) < 10000 and BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal party = MEntityList(\"friendly,alive,chartype=4,myparty,targetable,maxdistance=\"..tostring(radius))\n\t\tif valid(party) then\n\t\t\t\tlocal HealerMimicry,count = HasBuffs(player,\"2126\"),0\n\t\t\t\tfor _,member in pairs(party) do\n\t\t\t\t\t\tif HasBuffs(member, table.concat(BLU.Settings.EsunaIDs,\",\")) then\n\t\t\t\t\t\t\t\treturn true,player\n\t\t\t\t\t\telseif HealerMimicry and member.hp.percent < BLU.Settings.partyAoECurePercent then\n\t\t\t\t\t\t\t\tcount = count + 1\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\t\t\tif count > 1 then\n\t\t\t\t\t\treturn true,player\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Esuna and AoE Cure --",
		[18319] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18319)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and MissingBuffs(player,\"167+1716\") then\n\t\tif valid(target) then\n  \t\tif BLU.ValidEntity(player,target,target,range) then\n    \t\treturn true,target\n  \t\tend\n\t\tend\n\t\t-- if valid(el) then\n\t\t-- \t\tfor id,entity in pairs(el) do\n\t\t-- \t\t\t\tif BLU.ValidEntity(player,target,entity,range) then\n\t\t-- \t\t\t\t\t\treturn true,entity\n\t\t-- \t\t\t\tend\n\t\t-- \t\tend\n\t\t-- end\n\nend\nreturn false",
		[18320] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18320)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and MissingBuffs(player,\"167+1716\") then\n\t\t-- local tankBuffs = HasBuffs(player,\"1710+2124\")\n\t\tlocal hpp = player.hp.percent\n\t\tif valid(target) and BLU.ValidEntity(player,target,target,range) then\n\t\t\t\tif target.targetid == player.id and hpp <= BLU.Settings.tankCurePercent then\n\t\t\t\t\t\treturn true,target\n\t\t\t\telseif hpp <= BLU.Settings.playerCurePercent then\n\t\t\t\t\t\treturn true,target\n\t\t\t\tend\n\t\telseif valid(el) then\n\t\t\t\tfor _,entity in pairs(el) do\n\t\t\t\t\t\tif entity.incombat and BLU.ValidEntity(player,target,entity,range) then\n\t\t\t\t\t\t\t\tif entity.targetid == player.id and hpp <= BLU.Settings.tankCurePercent then\n\t\t\t\t\t\t\t\t\t\treturn true,entity\n\t\t\t\t\t\t\t\telseif hpp <= BLU.Settings.playerCurePercent then\n\t\t\t\t\t\t\t\t\t\treturn true,entity\n\t\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Increases max HP by 20% (15s) and restores HP equal to damage dealt --",
		[18321] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18321)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(target) and MissingBuffs(player,167+1716) and MissingBuffs(player,167+1716) then\n    local check = function(entity)\n      if MissingBuffs(entity,\"2121+2122+2123\",4) then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n    if BLU.ValidEntity(player,target,target,range,check) then\n        return true,target\n    end\nend\nreturn false",
		[18322] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18322)\n--- DO NOT EDIT ABOVE THIS LINE ---\n\nlocal name = BLU.Settings.Toggles[2].name\nlocal buffs = Player.buffs\nlocal buff = 0\n\nif valid(buffs) then\n\t\tfor index,Buff in pairs(buffs) do\n\t\t\t\tlocal id = Buff.id\n\t\t\t\tif BLU.Is(id,2124,2125,2126) then\n\t\t\t\t\t\tbuff = id\n\t\t\t\tend\n\t\tend\nend\n\nlocal search,role = false,\"\"\nif name == \"DPS\" and buff ~= 2125 then search,role = true,\"DPS\"\nelseif name == \"Healer\" and buff ~= 2126 then search,role = true,\"Healer\"\nelseif name == \"Tank\" and buff ~= 2124 then search,role = true,\"Tank\"\nend\n\nif search then\n\t\tlocal friendlies = MEntityList(\"friendly,alive,chartype=4,los,targetable,maxdistance=25\")\n\t\tif valid(friendlies) then\n\t\t\t\tfor id,friendly in pairs(friendlies) do\n\t\t\t\t\t\tlocal friendlyRole = GetRoleString(friendly.job)\n\t\t\t\t\t\tif friendlyRole == role then\n\t\t\t\t\t\t\t\treturn true,friendly\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t\tend\nend\nreturn false",
		[18323] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18323)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(target) and MissingBuffs(player,\"167+1716\") then\n\t\tSendTextCommand(\"/battlemode off\")\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,0)\nend\nreturn false",
		[18324] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18324)\n--- DO NOT EDIT ABOVE THIS LINE ---\n\nif BLU.Settings.Toggles[2].enable and valid(el) then\n\t\tlocal count = 0\n\t\tfor _,entity in pairs(el) do\n    local check = function(entity)\n\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end\n\t\t\t\tif BLU.ValidEntity(player,target,entity,radius,check) then\n\t\t\t\t\t\tcount = count + 1\n\t\t\t\tend\n\t\tend\n\t\tif count > 1 then\n\t\t\t\treturn true,player\n\t\tend\nend\nreturn false\n\n-- AoE around Player --",
		[18325] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18325)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[3].enable and valid(el) and NotBound() then\n    local check = function(entity)\n\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end\n    local result,pos,id = BLU.ElGroundCheck(el,player,target,range,radius,2,check)\n    if result then\n        return true,pos\n    end\nend\nreturn false\n\n-- Jumping Ground AoE Attack --",
		[107561] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(7561)\n--- DO NOT EDIT ABOVE THIS LINE ---",
		[111384] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11384)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n    local check = function(entity)\n\t\t\t\t\t\tlocal ValidEntities = {}\n      if valid(ValidEntities) and table.contains(ValidEntities,entity.contentid) and MissingBuffs(entity,14,3) then\n\t\t\t\t\t\t\t\treturn BLU.HpAdvantage(entity) end end\n\t\treturn BLU.ElGroundCheck(el,player,target,range,radius,2,check)\nend\nreturn false",
		[111385] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11385)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and valid(target) and player.incombat then\n  local check = function(entity)\n\t\t\t\tlocal CIDs = {9246}\n\t\t\t\tif table.contains(CIDs,entity.contentid) then return true end end\n  if BLU.ValidEntity(player,target,target,range,check) then\n    return true,target\n  end\nend\nreturn false",
		[111396] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11396)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\tlocal check = function(entity)\n\t\t\t\tif MissingBuffs(entity,\"2\",1) then return true end end\n\t\treturn BLU.ElGroundCheck(el,player,target,range,radius,2,check)\nend\nreturn false\n\n-- Stuns all enemies in a circle at a designated location --",
		[111397] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11397)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Settings.Toggles[2].enable and BLU.Not(lastcast,11393) and valid(el) and MissingBuffs(player,\"1716\") then\n\t\treturn true,player\nend\nreturn false\n\n-- Does a flat 1000 damage split between all enemies around Player --",
		[111400] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11400)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and MissingBuffs(player,\"167+1716\") then\n\t\tif valid(target) then\n  \t\tif BLU.ValidEntity(player,target,target,range) then\n    \t\treturn true,target\n  \t\tend\n\t\tend\n\t\t-- if valid(el) then\n\t\t-- \t\tfor id,entity in pairs(el) do\n\t\t-- \t\t\t\tif BLU.ValidEntity(player,target,entity,range) then\n\t\t-- \t\t\t\t\t\treturn true,entity\n\t\t-- \t\t\t\tend\n\t\t-- \t\tend\n\t\t-- end\n\nend\nreturn false",
		[111404] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11404)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,0)\nend\nreturn false\n\n-- backup if nothing else works --",
		[111425] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(11425)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and valid(el) and MissingBuffs(player,\"167\") then\n    local result,pos,id = BLU.ElGroundCheck(el,player,target,range,radius,2)\n    if result then\n        return true,pos\n    end\nend\nreturn false",
		[118295] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18295)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElLineCheck(el,player,target,0.25,range,2)\nend\nreturn false",
		[118298] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18298)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(el) and MissingBuffs(player,\"167+1716\") then\n\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,2)\nend\nreturn false",
		[118300] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18300)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561,11393) and valid(target) and MissingBuffs(player,\"167+1716\") then\n  if BLU.ValidEntity(player,target,target,range) then\n    return true,target\n\t\tend\nend\nreturn false",
		[118308] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18308)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif BLU.Not(lastcast,7561) and MissingBuffs(player,\"167+1716\") then\n\t\tif valid(target) then\n  \t\tif BLU.ValidEntity(player,target,target,range) then\n    \t\treturn true,target\n  \t\tend\n\t\tend\n\t\t-- if valid(el) then\n\t\t-- \t\tfor id,entity in pairs(el) do\n\t\t-- \t\t\t\tif BLU.ValidEntity(player,target,entity,range) then\n\t\t-- \t\t\t\t\t\treturn true,entity\n\t\t-- \t\t\t\tend\n\t\t-- \t\tend\n\t\t-- end\n\nend\nreturn false",
		[118323] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18323)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif HasBuffs(player,2130) or LastCast < 1250 or player.castinginfo.castingid == 18323 then\n\t\tif valid(target) then\n  \t\tif BLU.ValidEntity(player,target,target,range) then\n\t\t\t\t\t\tSendTextCommand(\"/battlemode off\")\n    \t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,0)\n  \t\tend\n\t\telseif valid(el) then\n\t\t\t\tfor id,entity in pairs(el) do\n\t\t\t\t\t\tif BLU.ValidEntity(player,target,entity,range) then\n\t\t\t\t\t\t\t\tSendTextCommand(\"/battlemode off\")\n\t\t\t\t\t\t\t\treturn BLU.ElConeCheck(0.251,el,player,target,radius,0)\n\t\t\t\t\t\tend\n\t\t\t\tend\n\t end\nend\nreturn false",
		[218300] = "local action, actiondata, actiondelay, LastCast, lastcast, lastGCDcast, range, radius, delay, precast, player, target, el, valid = BLU.vars(18300)\n--- DO NOT EDIT ABOVE THIS LINE ---\nif valid(2,el,target) then\n\t\tfor id,entity in pairs(el) do\n\t\t\t\tlocal FocusTargets = {8130,3777}\n\t\t\t\tif table.contains(FocusTargets,entity.contentid) then\n\t\t\t\t\t\treturn true,entity\n\t\t\t\tend\n\t\tend\nend\nreturn false\n\n-- Prioritized physical ranged attack for certain enemies --",
	},
	ActionPriority = 
	{
		18322,
		11424,
		118323,
		11423,
		11403,
		11396,
		18314,
		18317,
		18307,
		11412,
		18315,
		18306,
		18302,
		11392,
		18301,
		18318,
		18303,
		11406,
		18304,
		7562,
		11395,
		218300,
		11418,
		11431,
		11410,
		11417,
		18320,
		7560,
		11421,
		11411,
		11388,
		18321,
		111384,
		18313,
		18312,
		11414,
		11415,
		11429,
		11428,
		11430,
		11398,
		11426,
		18325,
		18324,
		18305,
		11399,
		11420,
		18297,
		11404,
		11390,
		11419,
		11402,
		11391,
		18295,
		18296,
		18298,
		18299,
		118297,
		11384,
		111396,
		111398,
		18323,
		11425,
		18310,
		18311,
		11422,
		11387,
		11389,
		11427,
		11394,
		18316,
		11400,
		11416,
		11405,
		11413,
		11386,
		18300,
		18319,
		111400,
		118300,
		18308,
		11385,
		111385,
		118298,
		111425,
		111397,
		118295,
		118308,
		118316,
		11397,
		11383,
		11401,
		7559,
		18309,
		11407,
		11408,
		11409,
		111404,
	},
	Actions = 
	{
		[7559] = false,
		[7560] = false,
		[7561] = true,
		[7562] = true,
		[11383] = false,
		[11384] = true,
		[11385] = true,
		[11386] = true,
		[11387] = true,
		[11388] = true,
		[11389] = true,
		[11390] = true,
		[11391] = true,
		[11392] = false,
		[11393] = true,
		[11394] = true,
		[11395] = true,
		[11396] = true,
		[11397] = true,
		[11398] = true,
		[11399] = true,
		[11400] = true,
		[11401] = false,
		[11402] = true,
		[11403] = true,
		[11404] = true,
		[11405] = true,
		[11406] = true,
		[11407] = false,
		[11408] = false,
		[11409] = false,
		[11410] = true,
		[11411] = true,
		[11412] = false,
		[11413] = true,
		[11414] = false,
		[11415] = false,
		[11416] = true,
		[11417] = false,
		[11418] = true,
		[11419] = true,
		[11420] = true,
		[11421] = true,
		[11422] = true,
		[11423] = true,
		[11424] = true,
		[11425] = true,
		[11426] = true,
		[11427] = true,
		[11428] = true,
		[11429] = true,
		[11430] = true,
		[11431] = true,
		[18295] = true,
		[18296] = true,
		[18297] = true,
		[18298] = true,
		[18299] = true,
		[18300] = true,
		[18301] = false,
		[18302] = true,
		[18303] = true,
		[18304] = true,
		[18305] = true,
		[18306] = false,
		[18307] = false,
		[18308] = true,
		[18309] = false,
		[18310] = true,
		[18311] = true,
		[18312] = false,
		[18313] = true,
		[18314] = true,
		[18315] = false,
		[18316] = false,
		[18317] = true,
		[18318] = true,
		[18319] = true,
		[18320] = true,
		[18321] = true,
		[18322] = true,
		[18323] = true,
		[18324] = true,
		[18325] = true,
		[107561] = true,
		[111384] = true,
		[111385] = false,
		[111396] = true,
		[111397] = true,
		[111398] = false,
		[111400] = true,
		[111404] = false,
		[111425] = true,
		[118295] = true,
		[118297] = true,
		[118298] = true,
		[118300] = true,
		[118308] = true,
		[118316] = false,
		[118323] = true,
		[211396] = true,
		[218298] = false,
		[218300] = true,
		[311396] = true,
	},
	BristleActions = 
	{
		[11386] = true,
	},
	CureOutsideParty = false,
	DiamondbackAoEIDs = 
	{
		18965,
		5973,
	},
	DiamondbackTargetIDs = 
	{
		18965,
		5973,
	},
	DispelIDs = 
	{
		63,
		1797,
	},
	DrawCone = false,
	DrawHotbar = true,
	DrawNearbyEnemyCircles = true,
	DrawToggles = true,
	EsunaIDs = 
	{
		14,
		271,
		564,
		700,
	},
	HotbarSettings = 
	{
		BackgroundTransparency = 115,
		ButtonHeight = 45,
		ButtonWidth = 42,
		CheckUpdateInterval = 5000,
		Columns = 12,
		HorizontalSpacing = 4,
		VerticalSpacing = 4,
		WindowPadding = 14,
	},
	InterruptIDs = 
	{
		14265,
		14365,
		14369,
		14680,
		14712,
		14720,
		14744,
		14890,
		15045,
		15049,
		15063,
		15318,
		15321,
	},
	PrecastTime = 250,
	RaiseOutsideParty = false,
	SlideCastTime = 490,
	StunCastingIDs = 
	{
		14753,
	},
	SwiftCastActions = 
	{
		[7561] = false,
		[11397] = true,
		[11423] = false,
		[18303] = false,
		[18317] = true,
		[18322] = true,
	},
	SwiftCastOptionalActions = 
	{
		[18322] = true,
	},
	ToggleSettings = 
	{
		BackgroundTransparency = 115,
		ButtonHeight = 30,
		ButtonWidth = 103,
		Columns = 3,
		DisabledColor = 
		{
			a = 191,
			b = 0,
			g = 0,
			r = 25,
		},
		EnabledColor = 
		{
			a = 191,
			b = 0,
			g = 25,
			r = 0,
		},
		HorizontalSpacing = 3,
		VerticalSpacing = 5,
	},
	Toggles = 
	{
		
		{
			enable = false,
			name = "HP Advantage",
		},
		
		{
			enable = true,
			name = "DPS",
		},
		
		{
			enable = true,
			name = "AoE",
		},
		
		{
			enable = true,
			name = "Jumping",
		},
		
		{
			enable = true,
			name = "Magical",
		},
		
		{
			enable = true,
			name = "Physical",
		},
		
		{
			enable = false,
			name = "Low Chance",
		},
	},
	hpAdvParty = 3,
	hpAdvSolo = 1,
	open = true,
	partyAoECurePercent = 70,
	partyCurePercent = 50,
	playerCurePercent = 60,
	playerRestoreMpPercent = 15,
	playerSpikeBuffAttacksLT = 90,
	playerTankRestoreMpPercent = 30,
	tankCurePercent = 70,
}



return tbl